### ISSUE TITLE
App Crashing 

### ISSUE THREAD

**Issue by hemrajKumawat1** [afreakyelf/Pdf-Viewer#73] opened 2023-07-06 08:25 UTC
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.rsmssb.oldpaper/com.rajat.pdfviewer.PdfViewerActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.ProgressBar.setVisibility(int)' on a null object reference

and using this 

    implementation 'com.github.afreakyelf:Pdf-Viewer:1.1.2'

  startActivity(PdfViewerActivity.Companion.launchPdfFromUrl(PdfViewer.this, path, "PDF", "", false)
                    .addFlags(Intent.FLAG_ACTIVITY_NEW_TASK));

**Comment by eduyash09** [comment] 2023-07-26 07:14
Any updates, or this library is deprecated?

**Comment by afreakyelf** [comment] 2023-11-29 03:29
Hi, Thank you for using this library. Above issue has been fixed in latest version. 
https://github.com/afreakyelf/Pdf-Viewer/releases/tag/v2.0.1

**Closed by afreakyelf** 2023-11-29 03:29 UTC
Labels: Fixed

**Comment by IlhomSh** [comment] 2024-04-24 08:32
Hello, I have the same error!

version I have v2.0.5
Caused by java.lang.NullPointerException:
       at com.rajat.pdfviewer.PdfViewerActivity.onCreate(PdfViewerActivity.kt:226)
